package db

var Schema = `
CREATE TABLE IF NOT EXISTS CLIPS (
	ID VARCHAR(36) PRIMARY KEY,
	CLIP TEXT NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	ATTACHMENT_TYPE VARCHAR(255),
	ATTACHMENT_ID VARCHAR(255)
);
`
