-- Your SQL goes here
CREATE TABLE IF NOT EXISTS CLIP (
Id VARCHAR(36) PRIMARY KEY,
Content TEXT NOT NULL,
AttachemtType TEXT,
AttachmentID TEXT UNIQUE
-- CREATED_AT TIMESTAMP NOT NULL,
-- UPDATED_AT TIMESTAMP 
);